apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileshare-ingress
  namespace: fileshare
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-clusterissuer"  # 指定 ClusterIssuer
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
    - demo-11-3.azure.seems.fit
    secretName: fileshare-tls-cf  
  rules:
  - host: demo-11-3.azure.seems.fit
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fileshare-svc
            port:
              name: http
