namespace: fileshare

service:
  name: fileshare-svc
  portName: http

ingress:
  enabled: true
  className: azure-application-gateway
  host: demo-11-3.azure.seems.fit          # 默认值，后面会被 ArgoCD 覆盖
  tlsSecret: fileshare-tls-cf
  clusterIssuer: cloudflare-clusterissuer
