apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          volumeMounts:
            - name: fileshare-data
              mountPath: {{ .Values.deployment.mountPath }}
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.health.path }}
              port: {{ .Values.deployment.containerPort }}
            initialDelaySeconds: {{ .Values.deployment.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.health.periodSeconds }}
      volumes:
        - name: fileshare-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
